# Generated by Django 6.0.2 on 2026-02-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
