# Generated by Django 6.0.2 on 2026-02-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='template',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
