# Generated by Django 6.0.2 on 2026-02-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('classic', 'Classic stil')], default='default', max_length=50),
        ),
    ]
