# Generated by Django 6.0.2 on 2026-02-26 21:13

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Objavljen'), ('draft', 'Skica'), ('deleted', 'Obrisan')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[blog.models.validate_image_size]),
        ),
    ]
