# Generated by Django 6.0.2 on 2026-02-28 09:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_status_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[blog.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
