# Generated by Django 6.0.2 on 2026-02-28 11:21

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_profile_pending_email_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[blog.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('classic', 'Classic stil')], default='default', max_length=50),
        ),
    ]
