# Generated by Django 6.0.2 on 2026-02-28 23:25

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_profile_avatar_alter_profile_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[blog.models.validate_image_size]),
        ),
    ]
