# Generated by Django 6.0.2 on 2026-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(blank=True, choices=[('znanje', 'Znanost & Znanje'), ('zivot', 'Život & Psihologija'), ('drustvo', 'Društvo'), ('kultura', 'Kultura & Kreativnost'), ('priroda', 'Priroda'), ('razno', 'Razno')], max_length=20, null=True),
        ),
    ]
