# Generated by Django 6.0.2 on 2026-03-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_category_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='home_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
