# Generated by Django 6.0.2 on 2026-03-04 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('daily', 'Post dana'), ('weekly', 'Post tjedna')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='blog.post')),
            ],
            options={
                'unique_together': {('kind', 'period_start')},
            },
        ),
    ]
