# Generated by Django 6.0.2 on 2026-03-05 18:51

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_rename_content_sitemessage_content_html_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='sitemessage',
            name='title',
        ),
        migrations.AlterField(
            model_name='sitemessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_messages/', validators=[blog.models.validate_image_size]),
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.DeleteModel(
            name='FeaturedPost',
        ),
    ]
