# Generated by Django 6.0.2 on 2026-03-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_featuredpost'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='featuredpost',
            name='blog_featur_kind_537cda_idx',
        ),
        migrations.RemoveField(
            model_name='featuredpost',
            name='post',
        ),
        migrations.DeleteModel(
            name='UserBlock',
        ),
        migrations.DeleteModel(
            name='FeaturedPost',
        ),
    ]
