# Generated by Django 6.0.2 on 2026-03-05 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_remove_featuredpost_blog_featur_kind_537cda_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('daily', 'Dnevni'), ('weekly', 'Tjedni')], max_length=10)),
                ('period_start', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='blog.post')),
            ],
            options={
                'indexes': [models.Index(fields=['kind', '-period_start'], name='blog_featur_kind_537cda_idx')],
            },
        ),
    ]
