# Generated by Django 6.0.2 on 2026-03-08 21:37

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_specialdayevent_specialdaymessage_specialdayselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blog_banner',
            field=models.ImageField(blank=True, null=True, upload_to='blog_banners/', validators=[blog.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='profile',
            name='blog_banner_position',
            field=models.CharField(choices=[('left', 'Lijevo'), ('center', 'Sredina'), ('right', 'Desno')], default='center', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark stil'), ('classic', 'Classic stil')], default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialdayevent',
            name='date_type',
            field=models.CharField(choices=[('fixed', 'Fiksni datum'), ('range', 'Raspon datuma'), ('nth_weekday', 'N-ti dan u mjesecu'), ('easter', 'Uskrs'), ('advent', 'Advent'), ('advent_sunday', 'Došašće (1.–4. nedjelja)')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='specialdayevent',
            name='position',
            field=models.CharField(choices=[('top', 'Iznad postova'), ('left', 'Iznad lijevog sidebara'), ('right', 'Iznad desnog sidebara')], default='top', max_length=10),
        ),
        migrations.AlterField(
            model_name='specialdayevent',
            name='theme',
            field=models.CharField(choices=[('general', 'Općenito'), ('romance', 'Valentinovo / romantika'), ('womens_day', 'Dan žena'), ('spring', 'Proljeće'), ('earth', 'Dan planeta Zemlje'), ('books', 'Dan knjige'), ('summer', 'Ljeto'), ('autumn', 'Jesen'), ('bread', 'Dani kruha'), ('advent', 'Advent'), ('advent_candle_1', 'Došašće – 1. svijeća'), ('advent_candle_2', 'Došašće – 2. svijeća'), ('advent_candle_3', 'Došašće – 3. svijeća'), ('advent_candle_4', 'Došašće – 4. svijeća'), ('christmas', 'Božić'), ('easter', 'Uskrs'), ('new_year', 'Nova godina'), ('old_year', 'Stara godina')], default='general', max_length=20),
        ),
    ]
