# Generated by Django 6.0.2 on 2026-03-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_special_day_event_special_day_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark stil')], default='default', max_length=50),
        ),
    ]
