# Generated by Django 6.0.2 on 2026-04-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_homefeaturedpost'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogvisitor',
            new_name='blog_blogvi_blog_ow_8cd797_idx',
            old_name='blog_blogvi_blog_ow_6bc38a_idx',
        ),
        migrations.RenameIndex(
            model_name='blogvisitor',
            new_name='blog_blogvi_blog_ow_7a3507_idx',
            old_name='blog_blogvi_blog_ow_2585a8_idx',
        ),
        migrations.RenameIndex(
            model_name='homefeaturedpost',
            new_name='blog_homefe_source_7a4801_idx',
            old_name='blog_homefe_source_a27bd6_idx',
        ),
        migrations.RenameIndex(
            model_name='homefeaturedpost',
            new_name='blog_homefe_slot_da_1be08a_idx',
            old_name='blog_homefe_slot_da_b1aa15_idx',
        ),
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark'), ('classic', 'Classic'), ('default_right', 'Default Plus'), ('dark_right', 'Dark Plus'), ('classic_right', 'Classic Plus'), ('simple_pattern', 'Simple Uzorak'), ('simple_image', 'Simple Slika'), ('simple_retro', 'Simple Retro'), ('soho', 'Studio'), ('magazin', 'Magazin'), ('litica_noci', 'Litica u noći'), ('podvodna_tisina', 'Podvodna tišina'), ('vodopad_u_magli', 'Vodopad u magli'), ('planine_u_magli', 'Planine u magli'), ('nebeski_mir', 'Nebeski mir'), ('svemirski_horizont', 'Svemirski horizont'), ('zlatni_horizont', 'Zlatni horizont'), ('iznad_oblaka', 'Iznad oblaka'), ('sumska_svjetlost', 'Šumska svjetlost'), ('polarna_svjetlost', 'Polarna svjetlost'), ('zlatno_polje', 'Zlatno polje'), ('neonski_grad', 'Neonski grad'), ('polje_lavande', 'Polje lavande'), ('carobna_ljubicasta', 'Čarobni sumrak'), ('kraljevska_pozornica', 'Kraljevska pozornica'), ('dimni_akordi', 'Dimni akordi'), ('nebeska_klasika', 'Nebeska klasika'), ('ponocna_elegancija', 'Ponoćna elegancija'), ('ruzicasti_vrt', 'Ružičasti vrt'), ('stara_aleja', 'Stara aleja'), ('staza_prema_vrhovima', 'Staza prema vrhovima'), ('jedro_u_suton', 'Jedro u suton'), ('misticno_jezero', 'Mistična laguna'), ('sjene_ulice', 'Sjene ulice'), ('mjesecev_ples', 'Mjesečev ples'), ('asfaltni_plamen', 'Asfaltni plamen')], default='default', max_length=50),
        ),
    ]
