# Generated by Django 6.0.2 on 2026-05-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_rename_blog_securi_event_t_4a6a7a_idx_blog_securi_event_t_7a9172_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='anonymize_after',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='anonymized_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Uspješna prijava'), ('login_failed', 'Neuspješna prijava'), ('login_lockout', 'Blokirana prijava'), ('registration_success', 'Uspješna registracija'), ('registration_blocked', 'Blokirana registracija'), ('turnstile_failed', 'Turnstile nije prošao'), ('activation_success', 'Račun aktiviran'), ('activation_failed', 'Neuspješna aktivacija'), ('resend_email_success', 'Ponovno poslan email'), ('resend_email_blocked', 'Blokirano ponovno slanje emaila'), ('password_change_success', 'Lozinka promijenjena'), ('password_change_failed', 'Neuspješna promjena lozinke'), ('email_change_requested', 'Zatražena promjena emaila'), ('email_change_confirmed', 'Email potvrđen'), ('comment_rate_limited', 'Komentiranje ograničeno'), ('duplicate_comment_blocked', 'Dupli komentar blokiran'), ('post_deleted', 'Post izbrisan'), ('avatar_deleted', 'Avatar izbrisan'), ('suspicious_access', 'Sumnjiv pristup')], max_length=60),
        ),
    ]
