# Generated by banner clean all-in-one fix

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0067_remove_profile_anonymize_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blog_banner_size',
            field=models.CharField(
                max_length=10,
                choices=[
                    ('xsmall', 'Vrlo malo'),
                    ('small', 'Malo'),
                    ('medium', 'Srednje'),
                    ('large', 'Veliko'),
                ],
                default='medium',
            ),
        ),
    ]
