# Generated by Django 6.0.2 on 2026-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0068_profile_blog_banner_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blog_banner_size',
        ),
        migrations.AlterField(
            model_name='profile',
            name='blog_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
