# Generated by Django 6.0.2 on 2026-06-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0068_profile_blog_banner_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='blog_banner_size',
            field=models.CharField(choices=[('mini', 'Mini'), ('small', 'Malo'), ('medium', 'Srednje'), ('large', 'Veliko'), ('huge', 'Ogromno')], default='medium', max_length=10),
        ),
    ]
