# Generated by Django 6.0.2 on 2026-06-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_remove_profile_blog_banner_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blog_banner_size',
            field=models.CharField(blank=True, choices=[('xsmall', 'Vrlo malo'), ('small', 'Malo'), ('medium', 'Srednje'), ('large', 'Veliko')], default='medium', max_length=10),
        ),
    ]
