# Generated by Django 6.0.2 on 2026-06-21 12:53

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientMusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.SlugField(help_text='Stalni ID pjesme. Najbolje koristiti naziv datoteke bez .mp3. Ne mijenjaj ako je korisnici vec koriste.', max_length=220, unique=True)),
                ('title', models.CharField(max_length=180, verbose_name='Naziv')),
                ('category', models.CharField(choices=[('calm', 'Mirno i opustajuce'), ('romantic', 'Njezno i romanticno'), ('jazz', 'Jazz i lounge'), ('fantasy', 'Carobno i fantasy'), ('mystery', 'Tajanstveno i napeto'), ('cinematic', 'Putovanje i filmski ugodaj'), ('fun', 'Veselo i posebno')], default='calm', max_length=30, verbose_name='Kategorija')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Opis')),
                ('artist', models.CharField(blank=True, max_length=180, verbose_name='Autor')),
                ('artist_url', models.URLField(blank=True, max_length=500, verbose_name='Link autora')),
                ('source_name', models.CharField(blank=True, default='Pixabay', max_length=80, verbose_name='Izvor')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='Link izvora/licence')),
                ('license_label', models.CharField(blank=True, default='Pixabay licenca', max_length=120, verbose_name='Licenca')),
                ('audio_file', models.FileField(upload_to='ambient_music/', validators=[blog.models.validate_audio_size], verbose_name='Audio datoteka')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Redoslijed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dodano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Azurirano')),
            ],
            options={
                'verbose_name': 'Ambijentalna glazba',
                'verbose_name_plural': 'Ambijentalna glazba',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
