# Generated by Django 6.0.2 on 2026-06-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0072_ambientmusictrack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktivan'), ('deactivated', 'Deaktiviran'), ('delete_requested', 'Zatraženo brisanje')], default='active', max_length=30)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_requested_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_status_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status korisničkog računa',
                'verbose_name_plural': 'Statusi korisničkih računa',
            },
        ),
    ]
