# Generated by Django 6.0.2 on 2026-06-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0074_blog_design_preferences_db'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('mention', 'Mention')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blog_banner_size',
            field=models.CharField(blank=True, choices=[('xsmall', 'Vrlo malo'), ('small', 'Malo'), ('medium', 'Srednje'), ('large', 'Veliko'), ('full_width', 'Puna širina')], default='medium', max_length=10),
        ),
    ]
