MONTHS_HR = {
    1: 'siječanj',
    2: 'veljača',
    3: 'ožujak',
    4: 'travanj',
    5: 'svibanj',
    6: 'lipanj',
    7: 'srpanj',
    8: 'kolovoz',
    9: 'rujan',
    10: 'listopad',
    11: 'studeni',
    12: 'prosinac',
}

CATEGORY_FOLDER_MAP = {
    'Znanost': 'znanost_znanje/znanost',
    'Edukacija': 'znanost_znanje/edukacija',
    'Tehnologija': 'znanost_znanje/tehnologija',
    'Povijest': 'znanost_znanje/povijest',
    'Politika': 'drustvo/politika',
    'Ekonomija': 'drustvo/ekonomija',
    'Zajednica': 'drustvo/zajednica',
    'Religija': 'drustvo/religija',
    'Filozofija': 'drustvo/filozofija',
    'Ljubav': 'zivot_psihologija/ljubav',
    'Odnosi': 'zivot_psihologija/odnosi',
    'Osobno': 'zivot_psihologija/osobno',
    'Psihologija': 'zivot_psihologija/psihologija',
    'Poezija': 'kultura_kreativnost/poezija',
    'Priče': 'kultura_kreativnost/price',
    'Price': 'kultura_kreativnost/price',
    'Umjetnost': 'kultura_kreativnost/umjetnost',
    'Arhitektura': 'kultura_kreativnost/arhitektura',
    'Fotografije': 'kultura_kreativnost/fotografije',
    'Glazba': 'kultura_kreativnost/glazba',
    'Film_Serije': 'kultura_kreativnost/film_serije',
    'Kazaliste': 'kultura_kreativnost/Kazaliste',
    'Zivotinje': 'priroda/zivotinje',
    'Biljke': 'priroda/biljke',
    'Pejzaz': 'priroda/pejzaz',
    'Recenzije': 'razno/recenzije',
    'Kviz': 'razno/kviz',
    'Anketa': 'razno/anketa',
    'Moda': 'razno/moda',
    'Putovanje': 'razno/putovanje',
    'Gastro': 'razno/gastro',
}
