# Auto-generated ambient music library metadata.

AMBIENT_MUSIC_CATEGORIES = [{'value': 'calm', 'label': 'Mirno i opuštajuće', 'description': 'Tiše i laganije melodije za čitanje.'},
 {'value': 'romantic', 'label': 'Nježno i romantično', 'description': 'Toplije, emotivne i mekše melodije.'},
 {'value': 'jazz', 'label': 'Jazz i lounge', 'description': 'Lagani jazz, lounge i večernja atmosfera.'},
 {'value': 'fantasy', 'label': 'Čarobno i fantasy', 'description': 'Bajkovita, mistična i čarobna glazba.'},
 {'value': 'mystery', 'label': 'Tajanstveno i napeto', 'description': 'Mračnije i napetije melodije.'},
 {'value': 'cinematic', 'label': 'Putovanje i filmski ugođaj', 'description': 'Širi, putopisni ili dokumentarni ton.'},
 {'value': 'fun', 'label': 'Veselo i posebno', 'description': 'Razigrane, tematske i posebne melodije.'}]

AMBIENT_MUSIC_TRACKS = [{'id': 'lvymusic-calm-background-for-video-121519',
  'title': 'Calm Background',
  'category': 'calm',
  'category_label': 'Mirno i opuštajuće',
  'description': 'Vrlo neutralna i nenametljiva pozadina.',
  'artist': 'Yurii Kohut',
  'artist_url': 'https://pixabay.com/users/lvymusic-27953103/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=121519',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=121519',
  'license_label': 'Pixabay licenca',
  'filename': 'lvymusic-calm-background-for-video-121519.mp3',
  'static_path': 'blog/audio/library/lvymusic-calm-background-for-video-121519.mp3'},
 {'id': 'music_for_video-forest-lullaby-110624',
  'title': 'Forest Lullaby',
  'category': 'calm',
  'category_label': 'Mirno i opuštajuće',
  'description': 'Tiha šumska uspavanka, dobra za mirnije blogove.',
  'artist': 'music_for_video',
  'artist_url': 'https://pixabay.com/users/music_for_video-22579021/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=110624',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=110624',
  'license_label': 'Pixabay licenca',
  'filename': 'music_for_video-forest-lullaby-110624.mp3',
  'static_path': 'blog/audio/library/music_for_video-forest-lullaby-110624.mp3'},
 {'id': 'music_for_video-in-the-forest-ambient-acoustic-guitar-instrumental-background-music-for-videos-5718',
  'title': 'In the Forest',
  'category': 'calm',
  'category_label': 'Mirno i opuštajuće',
  'description': 'Akustična i opuštajuća pozadina s prirodnim ugođajem.',
  'artist': 'music_for_video',
  'artist_url': 'https://pixabay.com/users/music_for_video-22579021/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=5718',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=5718',
  'license_label': 'Pixabay licenca',
  'filename': 'music_for_video-in-the-forest-ambient-acoustic-guitar-instrumental-background-music-for-videos-5718.mp3',
  'static_path': 'blog/audio/library/music_for_video-in-the-forest-ambient-acoustic-guitar-instrumental-background-music-for-videos-5718.mp3'},
 {'id': 'the_mountain-relaxing-relaxing-music-492810',
  'title': 'Relaxing',
  'category': 'calm',
  'category_label': 'Mirno i opuštajuće',
  'description': 'Mirna glazba koja ostaje u pozadini.',
  'artist': 'Dmitrii Kolesnikov',
  'artist_url': 'https://pixabay.com/users/the_mountain-3616498/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=492810',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=492810',
  'license_label': 'Pixabay licenca',
  'filename': 'the_mountain-relaxing-relaxing-music-492810.mp3',
  'static_path': 'blog/audio/library/the_mountain-relaxing-relaxing-music-492810.mp3'},
 {'id': 'the_mountain-soft-background-music-492811',
  'title': 'Soft Background',
  'category': 'calm',
  'category_label': 'Mirno i opuštajuće',
  'description': 'Vrlo blaga instrumentalna pozadina za čitanje.',
  'artist': 'Dmitrii Kolesnikov',
  'artist_url': 'https://pixabay.com/users/the_mountain-3616498/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=492811',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=492811',
  'license_label': 'Pixabay licenca',
  'filename': 'the_mountain-soft-background-music-492811.mp3',
  'static_path': 'blog/audio/library/the_mountain-soft-background-music-492811.mp3'},
 {'id': 'andriig-soft-soft-music-507175',
  'title': 'Soft Music',
  'category': 'calm',
  'category_label': 'Mirno i opuštajuće',
  'description': 'Nježna i jednostavna pozadinska melodija.',
  'artist': 'andrii g.',
  'artist_url': 'https://pixabay.com/users/andriig-54059306/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=507175',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=507175',
  'license_label': 'Pixabay licenca',
  'filename': 'andriig-soft-soft-music-507175.mp3',
  'static_path': 'blog/audio/library/andriig-soft-soft-music-507175.mp3'},
 {'id': 'nastelbom-emotional-piano-495887',
  'title': 'Emotional Piano',
  'category': 'romantic',
  'category_label': 'Nježno i romantično',
  'description': 'Klavirska i emotivna glazba za topliji dojam.',
  'artist': 'Dmitrii Spis',
  'artist_url': 'https://pixabay.com/users/nastelbom-48128234/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=495887',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=495887',
  'license_label': 'Pixabay licenca',
  'filename': 'nastelbom-emotional-piano-495887.mp3',
  'static_path': 'blog/audio/library/nastelbom-emotional-piano-495887.mp3'},
 {'id': 'grand_project-my-love-medium-177577',
  'title': 'My Love',
  'category': 'romantic',
  'category_label': 'Nježno i romantično',
  'description': 'Romantična i mekša melodija.',
  'artist': 'Grand_Project',
  'artist_url': 'https://pixabay.com/users/grand_project-19033897/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=177577',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=177577',
  'license_label': 'Pixabay licenca',
  'filename': 'grand_project-my-love-medium-177577.mp3',
  'static_path': 'blog/audio/library/grand_project-my-love-medium-177577.mp3'},
 {'id': 'good_b_music-perfect-beauty-191271',
  'title': 'Perfect Beauty',
  'category': 'romantic',
  'category_label': 'Nježno i romantično',
  'description': 'Nježna i topla melodija za laganiji ugođaj.',
  'artist': 'Zakhar Valaha',
  'artist_url': 'https://pixabay.com/users/good_b_music-22836301/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=191271',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=191271',
  'license_label': 'Pixabay licenca',
  'filename': 'good_b_music-perfect-beauty-191271.mp3',
  'static_path': 'blog/audio/library/good_b_music-perfect-beauty-191271.mp3'},
 {'id': 'denis-pavlov-music-poetic-lyrical-beautiful-cinematic-piano-cello-music-482222',
  'title': 'Poetic Piano & Cello',
  'category': 'romantic',
  'category_label': 'Nježno i romantično',
  'description': 'Lirska kombinacija klavira i violončela.',
  'artist': 'Denis Pavlov',
  'artist_url': 'https://pixabay.com/users/denis-pavlov-music-35636692/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=482222',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=482222',
  'license_label': 'Pixabay licenca',
  'filename': 'denis-pavlov-music-poetic-lyrical-beautiful-cinematic-piano-cello-music-482222.mp3',
  'static_path': 'blog/audio/library/denis-pavlov-music-poetic-lyrical-beautiful-cinematic-piano-cello-music-482222.mp3'},
 {'id': 'the_mountain-sad-sad-music-490012',
  'title': 'Sad Mood',
  'category': 'romantic',
  'category_label': 'Nježno i romantično',
  'description': 'Emotivna i sporija glazba s nježnim tonom.',
  'artist': 'Dmitrii Kolesnikov',
  'artist_url': 'https://pixabay.com/users/the_mountain-3616498/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=490012',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=490012',
  'license_label': 'Pixabay licenca',
  'filename': 'the_mountain-sad-sad-music-490012.mp3',
  'static_path': 'blog/audio/library/the_mountain-sad-sad-music-490012.mp3'},
 {'id': 'djovan-easy-jazz-nights-497003',
  'title': 'Easy Jazz Nights',
  'category': 'jazz',
  'category_label': 'Jazz i lounge',
  'description': 'Večernji i lagani jazz ugođaj.',
  'artist': 'omar sahel',
  'artist_url': 'https://pixabay.com/users/djovan-36764943/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=497003',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=497003',
  'license_label': 'Pixabay licenca',
  'filename': 'djovan-easy-jazz-nights-497003.mp3',
  'static_path': 'blog/audio/library/djovan-easy-jazz-nights-497003.mp3'},
 {'id': 'tunetank-jazz-background-music-349165',
  'title': 'Jazz Background',
  'category': 'jazz',
  'category_label': 'Jazz i lounge',
  'description': 'Nenametljiva jazz podloga.',
  'artist': 'Tunetank',
  'artist_url': 'https://pixabay.com/users/tunetank-50201703/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=349165',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=349165',
  'license_label': 'Pixabay licenca',
  'filename': 'tunetank-jazz-background-music-349165.mp3',
  'static_path': 'blog/audio/library/tunetank-jazz-background-music-349165.mp3'},
 {'id': 'tunetank-jazz-cafe-music-348267',
  'title': 'Jazz Cafe',
  'category': 'jazz',
  'category_label': 'Jazz i lounge',
  'description': 'Ležerna café jazz atmosfera.',
  'artist': 'Tunetank',
  'artist_url': 'https://pixabay.com/users/tunetank-50201703/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=348267',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=348267',
  'license_label': 'Pixabay licenca',
  'filename': 'tunetank-jazz-cafe-music-348267.mp3',
  'static_path': 'blog/audio/library/tunetank-jazz-cafe-music-348267.mp3'},
 {'id': 'bransboynd-night-summer-lounge-473222',
  'title': 'Night Summer Lounge',
  'category': 'jazz',
  'category_label': 'Jazz i lounge',
  'description': 'Lounge atmosfera za toplije večeri.',
  'artist': 'Roman Rumyantsev',
  'artist_url': 'https://pixabay.com/users/bransboynd-51721546/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=473222',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=473222',
  'license_label': 'Pixabay licenca',
  'filename': 'bransboynd-night-summer-lounge-473222.mp3',
  'static_path': 'blog/audio/library/bransboynd-night-summer-lounge-473222.mp3'},
 {'id': 'denis-pavlov-music-relax-romantic-jazz-calm-soothing-home-295797',
  'title': 'Romantic Jazz',
  'category': 'jazz',
  'category_label': 'Jazz i lounge',
  'description': 'Topao jazz s mirnijim ritmom.',
  'artist': 'Denis Pavlov',
  'artist_url': 'https://pixabay.com/users/denis-pavlov-music-35636692/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=295797',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=295797',
  'license_label': 'Pixabay licenca',
  'filename': 'denis-pavlov-music-relax-romantic-jazz-calm-soothing-home-295797.mp3',
  'static_path': 'blog/audio/library/denis-pavlov-music-relax-romantic-jazz-calm-soothing-home-295797.mp3'},
 {'id': 'trycja-magic-night-463978',
  'title': 'Magic Night',
  'category': 'fantasy',
  'category_label': 'Čarobno i fantasy',
  'description': 'Čarobna i nježno mistična noćna atmosfera.',
  'artist': 'Trycja',
  'artist_url': 'https://pixabay.com/users/trycja-44180667/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=463978',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=463978',
  'license_label': 'Pixabay licenca',
  'filename': 'trycja-magic-night-463978.mp3',
  'static_path': 'blog/audio/library/trycja-magic-night-463978.mp3'},
 {'id': 'luis_humanoide-school-of-magic-inspired-by-harry-potter-289617',
  'title': 'School of Magic',
  'category': 'fantasy',
  'category_label': 'Čarobno i fantasy',
  'description': 'Čarobna škola i bajkovitiji ugođaj.',
  'artist': 'Luis Humanoide',
  'artist_url': 'https://pixabay.com/users/luis_humanoide-12661853/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=289617',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=289617',
  'license_label': 'Pixabay licenca',
  'filename': 'luis_humanoide-school-of-magic-inspired-by-harry-potter-289617.mp3',
  'static_path': 'blog/audio/library/luis_humanoide-school-of-magic-inspired-by-harry-potter-289617.mp3'},
 {'id': 'kaazoom-shadows-beneath-the-roots-fantasy-elvish-song-rpg-448106',
  'title': 'Shadows Beneath the Roots',
  'category': 'fantasy',
  'category_label': 'Čarobno i fantasy',
  'description': 'Fantasy / RPG ugođaj s mistikom i dubinom.',
  'artist': 'Paul Winter',
  'artist_url': 'https://pixabay.com/users/kaazoom-448850/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=448106',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=448106',
  'license_label': 'Pixabay licenca',
  'filename': 'kaazoom-shadows-beneath-the-roots-fantasy-elvish-song-rpg-448106.mp3',
  'static_path': 'blog/audio/library/kaazoom-shadows-beneath-the-roots-fantasy-elvish-song-rpg-448106.mp3'},
 {'id': 'lexin_music-the-moon-got-tangled-in-the-branches-155041',
  'title': 'The Moon Got Tangled in the Branches',
  'category': 'fantasy',
  'category_label': 'Čarobno i fantasy',
  'description': 'Sanjiva i čarobna melodija.',
  'artist': 'Aleksey Chistilin',
  'artist_url': 'https://pixabay.com/users/lexin_music-28841948/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=155041',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=155041',
  'license_label': 'Pixabay licenca',
  'filename': 'lexin_music-the-moon-got-tangled-in-the-branches-155041.mp3',
  'static_path': 'blog/audio/library/lexin_music-the-moon-got-tangled-in-the-branches-155041.mp3'},
 {'id': 'juliush-wark-in-a-park-piano-flute-orchestra-507409',
  'title': 'Wark in a Park',
  'category': 'fantasy',
  'category_label': 'Čarobno i fantasy',
  'description': 'Piano i flauta daju malo bajkovitiji osjećaj.',
  'artist': 'Julius H.',
  'artist_url': 'https://pixabay.com/users/juliush-3921568/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=507409',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=507409',
  'license_label': 'Pixabay licenca',
  'filename': 'juliush-wark-in-a-park-piano-flute-orchestra-507409.mp3',
  'static_path': 'blog/audio/library/juliush-wark-in-a-park-piano-flute-orchestra-507409.mp3'},
 {'id': 'luis_humanoide-creepy-halloween-orchestra-307180',
  'title': 'Creepy Halloween Orchestra',
  'category': 'mystery',
  'category_label': 'Tajanstveno i napeto',
  'description': 'Orkestralna i pomalo strašna glazba.',
  'artist': 'Luis Humanoide',
  'artist_url': 'https://pixabay.com/users/luis_humanoide-12661853/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=307180',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=307180',
  'license_label': 'Pixabay licenca',
  'filename': 'luis_humanoide-creepy-halloween-orchestra-307180.mp3',
  'static_path': 'blog/audio/library/luis_humanoide-creepy-halloween-orchestra-307180.mp3'},
 {'id': 'litesaturation-horror-474533',
  'title': 'Horror',
  'category': 'mystery',
  'category_label': 'Tajanstveno i napeto',
  'description': 'Napetija i tamnija glazba za strašniji ugođaj.',
  'artist': 'LiteSaturation',
  'artist_url': 'https://pixabay.com/users/litesaturation-17654080/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=474533',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=474533',
  'license_label': 'Pixabay licenca',
  'filename': 'litesaturation-horror-474533.mp3',
  'static_path': 'blog/audio/library/litesaturation-horror-474533.mp3'},
 {'id': 'lmnt_studio-the-mystery-409858',
  'title': 'The Mystery',
  'category': 'mystery',
  'category_label': 'Tajanstveno i napeto',
  'description': 'Tajanstvena pozadina s laganom napetošću.',
  'artist': 'LMNT_Studio',
  'artist_url': 'https://pixabay.com/users/lmnt_studio-52220287/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=409858',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=409858',
  'license_label': 'Pixabay licenca',
  'filename': 'lmnt_studio-the-mystery-409858.mp3',
  'static_path': 'blog/audio/library/lmnt_studio-the-mystery-409858.mp3'},
 {'id': 'solarflex-documentary-documentary-music-499243',
  'title': 'Documentary',
  'category': 'cinematic',
  'category_label': 'Putovanje i filmski ugođaj',
  'description': 'Čista i elegantna podloga za ozbiljniji ton.',
  'artist': 'SolarFLEX',
  'artist_url': 'https://pixabay.com/users/solarflex-54712313/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=499243',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=499243',
  'license_label': 'Pixabay licenca',
  'filename': 'solarflex-documentary-documentary-music-499243.mp3',
  'static_path': 'blog/audio/library/solarflex-documentary-documentary-music-499243.mp3'},
 {'id': 'the_mountain-hopeful-hopeful-music-492806',
  'title': 'Hopeful',
  'category': 'cinematic',
  'category_label': 'Putovanje i filmski ugođaj',
  'description': 'Pozitivna i lagano filmska melodija.',
  'artist': 'Dmitrii Kolesnikov',
  'artist_url': 'https://pixabay.com/users/the_mountain-3616498/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=492806',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=492806',
  'license_label': 'Pixabay licenca',
  'filename': 'the_mountain-hopeful-hopeful-music-492806.mp3',
  'static_path': 'blog/audio/library/the_mountain-hopeful-hopeful-music-492806.mp3'},
 {'id': 'alex_besss-middle-east-455259',
  'title': 'Middle East',
  'category': 'cinematic',
  'category_label': 'Putovanje i filmski ugođaj',
  'description': 'Egzotičniji i putopisni ugođaj.',
  'artist': 'ALEXEY BEZRUCHKO',
  'artist_url': 'https://pixabay.com/users/alex_besss-49928677/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=455259',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=455259',
  'license_label': 'Pixabay licenca',
  'filename': 'alex_besss-middle-east-455259.mp3',
  'static_path': 'blog/audio/library/alex_besss-middle-east-455259.mp3'},
 {'id': 'apalonbeats-travel-504929',
  'title': 'Travel',
  'category': 'cinematic',
  'category_label': 'Putovanje i filmski ugođaj',
  'description': 'Lagano pokretna glazba za putovanja i avanture.',
  'artist': 'APALONBeats',
  'artist_url': 'https://pixabay.com/users/apalonbeats-54803662/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=504929',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=504929',
  'license_label': 'Pixabay licenca',
  'filename': 'apalonbeats-travel-504929.mp3',
  'static_path': 'blog/audio/library/apalonbeats-travel-504929.mp3'},
 {'id': 'vasilyatsevich-carol-of-the-bells-christmas-epic-trailer-443834',
  'title': 'Carol of the Bells',
  'category': 'fun',
  'category_label': 'Veselo i posebno',
  'description': 'Svečanija i dramatičnija božićna tema.',
  'artist': 'Vasil Yatsevich',
  'artist_url': 'https://pixabay.com/users/vasilyatsevich-601514/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=443834',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=443834',
  'license_label': 'Pixabay licenca',
  'filename': 'vasilyatsevich-carol-of-the-bells-christmas-epic-trailer-443834.mp3',
  'static_path': 'blog/audio/library/vasilyatsevich-carol-of-the-bells-christmas-epic-trailer-443834.mp3'},
 {'id': 'starostin-comedy-cartoon-funny-background-music-492540',
  'title': 'Comedy Cartoon',
  'category': 'fun',
  'category_label': 'Veselo i posebno',
  'description': 'Vesela i luckasta glazba za opušteniji blog.',
  'artist': 'Viacheslav Starostin',
  'artist_url': 'https://pixabay.com/users/starostin-46826676/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=492540',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=492540',
  'license_label': 'Pixabay licenca',
  'filename': 'starostin-comedy-cartoon-funny-background-music-492540.mp3',
  'static_path': 'blog/audio/library/starostin-comedy-cartoon-funny-background-music-492540.mp3'},
 {'id': 'mondamusic-food-food-cooking-music-499162',
  'title': 'Cooking Music',
  'category': 'fun',
  'category_label': 'Veselo i posebno',
  'description': 'Topla i vesela glazba za gastro teme.',
  'artist': 'MondaMusic',
  'artist_url': 'https://pixabay.com/users/mondamusic-54713575/?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=499162',
  'source_name': 'Pixabay',
  'source_url': 'https://pixabay.com/music//?utm_source=link-attribution&utm_medium=referral&utm_campaign=music&utm_content=499162',
  'license_label': 'Pixabay licenca',
  'filename': 'mondamusic-food-food-cooking-music-499162.mp3',
  'static_path': 'blog/audio/library/mondamusic-food-food-cooking-music-499162.mp3'}]

AMBIENT_MUSIC_TRACK_MAP = {item["id"]: item for item in AMBIENT_MUSIC_TRACKS}


def _get_uploaded_ambient_tracks():
    """
    Glazba dodana kroz Django admin.
    Funkcija je namjerno ovdje, a import modela je unutra, da ne radi circular import.
    """
    try:
        from django.db.utils import OperationalError, ProgrammingError
        from .models import AmbientMusicTrack

        uploaded_tracks = []
        qs = AmbientMusicTrack.objects.filter(is_active=True).order_by("category", "title")

        for track in qs:
            audio_url = track.audio_file.url if track.audio_file else ""
            category_label = track.get_category_display()

            uploaded_tracks.append({
                "id": f"admin-{track.pk}",
                "title": track.title,
                "category": track.category,
                "category_label": category_label,
                "description": track.description or "Glazba dodana kroz admin.",
                "artist": track.artist or "BlogPlatform",
                "artist_url": "",
                "source_name": "Admin",
                "source_url": audio_url,
                "license_label": "Dodano u adminu",
                "filename": track.audio_file.name if track.audio_file else "",
                "static_path": "",
                "audio_url": audio_url,
                "is_uploaded": True,
            })

        return uploaded_tracks

    except (OperationalError, ProgrammingError):
        # Ako migracija još nije pokrenuta, nemoj srušiti stranicu.
        return []
    except Exception:
        return []


def get_ambient_music_tracks():
    static_tracks = []

    for item in AMBIENT_MUSIC_TRACKS:
        copied = dict(item)
        copied.setdefault("audio_url", "")
        copied.setdefault("is_uploaded", False)
        static_tracks.append(copied)

    return static_tracks + _get_uploaded_ambient_tracks()


def get_ambient_music_categories():
    categories = [dict(item) for item in AMBIENT_MUSIC_CATEGORIES]

    if not any(item.get("value") == "other" for item in categories):
        categories.append({
            "value": "other",
            "label": "Ostalo",
            "description": "Glazba dodana kroz admin."
        })

    return categories


def get_ambient_music_track(track_id):
    if not track_id:
        return None

    track_id = str(track_id).strip()

    if track_id.startswith("admin-"):
        try:
            pk = int(track_id.replace("admin-", "", 1))
        except Exception:
            return None

        for item in _get_uploaded_ambient_tracks():
            if item.get("id") == f"admin-{pk}":
                return dict(item)

        return None

    item = AMBIENT_MUSIC_TRACK_MAP.get(track_id)
    if not item:
        return None

    copied = dict(item)
    copied.setdefault("audio_url", "")
    copied.setdefault("is_uploaded", False)
    return copied
